export const nationalityOptions = [
  "American",
  "Canadian",
  "British",
  "Australian",
  "Indian",
  "Chinese",
  "Brazilian",
  "French",
  "German",
  "Japanese",
  "Mexican",
  "Italian",
  "Russian",
  "Spanish",
  "South African",
  "Nigerian",
  "Egyptian",
  "Argentinian",
  "Colombian",
  "Chilean",
  "Peruvian",
  "Venezuelan",
  "Dutch",
  "Belgian",
  "Swiss",
  "Austrian",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Polish",
  "Czech",
  "Hungarian",
  "Greek",
  "Turkish",
  "Saudi Arabian",
  "Emirati",
  "Israeli",
  "Thai",
  "Vietnamese",
  "Malaysian",
  "Indonesian",
  "Filipino",
  "South Korean",
  "Singaporean",
  "New Zealander",
  "Irish",
  "Portuguese",
  "Romanian",
  "Bulgarian"
];

export const genderOptions = [
  "Male",
  "Female",
  "Non-binary",
  "Bigender",
  "Prefer not to say"
];

export const nigerianAddresses = [
  "123 Lagos Street, Lagos",
  "456 Abuja Crescent, Abuja",
  "789 Port Harcourt Road, Port Harcourt",
  "101 Kano Avenue, Kano",
  "202 Ibadan Boulevard, Ibadan",
  "303 Enugu Lane, Enugu",
  "404 Benin City Drive, Benin City",
  "505 Jos Close, Jos",
  "606 Kaduna Street, Kaduna",
  "707 Warri Road, Warri"
];


export const notifications = [
  {
    id: 1,
    user: "Wenaija",
    handle: "@support",
    message: "Your report for Quotient Specialist Hospital has been submitted",
    time: "1 hr ago",
    read: false,
  },
  {
    id: 2,
    user: "Wenaija",
    handle: "@support",
    message: "Your KYC status is verified",
    time: "2 hr ago",
    read: true,
  },
  {
    id: 3,
    user: "Wenaija",
    handle: "@support",
    message: "Kindly upload your ID card to complete your KYC verification",
    time: "2 hr ago",
    read: false,
  },
  {
    id: 4,
    user: "Wenaija",
    handle: "@support",
    message:
      "Thank you for signing up successfully. Kindly begin your KYC verification",
    time: "4 hr ago",
    read: true,
  },
];
