export const hospitalData = [
    {
      id: 1,
      name: "Quotient Specialist Hospital",
      abbreviation: "QSH",
      address: "No 5, Lekki view, Lagos Island, Lagos state, Nigeria.",
      schedule: "Monday - Sunday",
      hours: "24 hours",
    },
    {
      id: 2,
      name: "Prime Health Clinic",
      abbreviation: "PHC",
      address: "Plot 12, Ajah Road, Lagos, Nigeria.",
      schedule: "Monday - Saturday",
      hours: "8 AM - 8 PM",
    },
    {
      id: 3,
      name: "City Hospital",
      abbreviation: "CH",
      address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
      schedule: "Monday - Friday",
      hours: "9 AM - 6 PM",
    },
    {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
      {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
      {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
      {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
      {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
      {
        id: 3,
        name: "City Hospital",
        abbreviation: "CH",
        address: "15 Admiralty Way, Ikoyi, Lagos, Nigeria.",
        schedule: "Monday - Friday",
        hours: "9 AM - 6 PM",
      },
  ];
  